# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Get Code 
      uses: actions/checkout@v3

    - name: Push Code to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIV_KEY }}
        REMOTE_HOST: vathzen.in
        REMOTE_USER: ubuntu
        TARGET: /home/ubuntu/go/EmoBot
